echo In test1
diff extra_output/output1.txt extra-test/test_1_s01.out
echo In test2
diff extra_output/output2.txt extra-test/test_1_s02.out
echo In test3
diff extra_output/output3.txt extra-test/test_1_s03.out
echo In test4
diff extra_output/output4.txt extra-test/test_1_s04.out
echo In test5
diff extra_output/output5.txt extra-test/test_1_s05.out
echo In test6
diff extra_output/output6.txt extra-test/test_1_s06.out
echo In test7
diff extra_output/output7.txt extra-test/test_1_s07.out
echo In test8
diff extra_output/output8.txt extra-test/test_1_s08.out
echo In test9
diff extra_output/output9.txt extra-test/test_1_s09.out
echo In test10
diff extra_output/output10.txt extra-test/test_1_s10.out
echo In test11
diff extra_output/output11.txt extra-test/test_1_s11.out
echo In test12
diff extra_output/output12.txt extra-test/test_1_s12.out
echo In test13
diff extra_output/output13.txt extra-test/test_1_s13.out
