bin/splc extra-test/test_1_s01.spl > extra_output/output1.txt
bin/splc extra-test/test_1_s02.spl > extra_output/output2.txt
bin/splc extra-test/test_1_s03.spl > extra_output/output3.txt
bin/splc extra-test/test_1_s04.spl > extra_output/output4.txt
bin/splc extra-test/test_1_s05.spl > extra_output/output5.txt
bin/splc extra-test/test_1_s06.spl > extra_output/output6.txt
bin/splc extra-test/test_1_s07.spl > extra_output/output7.txt
bin/splc extra-test/test_1_s08.spl > extra_output/output8.txt
bin/splc extra-test/test_1_s09.spl > extra_output/output9.txt
bin/splc extra-test/test_1_s10.spl > extra_output/output10.txt
bin/splc extra-test/test_1_s11.spl > extra_output/output11.txt
bin/splc extra-test/test_1_s12.spl > extra_output/output12.txt
bin/splc extra-test/test_1_s13.spl > extra_output/output13.txt