./bin/splc github_test/test_1_r01.spl > github_output/output1.txt
./bin/splc github_test/test_1_r02.spl > github_output/output2.txt
./bin/splc github_test/test_1_r03.spl > github_output/output3.txt
./bin/splc github_test/test_1_r04.spl > github_output/output4.txt
./bin/splc github_test/test_1_r05.spl > github_output/output5.txt
./bin/splc github_test/test_1_r06.spl > github_output/output6.txt
./bin/splc github_test/test_1_r07.spl > github_output/output7.txt
./bin/splc github_test/test_1_r08.spl > github_output/output8.txt
./bin/splc github_test/test_1_r09.spl > github_output/output9.txt
./bin/splc github_test/test_1_r10.spl > github_output/output10.txt
./bin/splc github_test/test_1_r11.spl > github_output/output11.txt
./bin/splc github_test/test_1_r12.spl > github_output/output12.txt