echo In test1
diff github_output/output1.txt github_test/test_1_r01.out
echo In test2
diff github_output/output2.txt github_test/test_1_r02.out
echo In test3
diff github_output/output3.txt github_test/test_1_r03.out
echo In test4
diff github_output/output4.txt github_test/test_1_r04.out
echo In test5
diff github_output/output5.txt github_test/test_1_r05.out
echo In test6
diff github_output/output6.txt github_test/test_1_r06.out
echo In test7
diff github_output/output7.txt github_test/test_1_r07.out
echo In test8
diff github_output/output8.txt github_test/test_1_r08.out
echo In test9
diff github_output/output9.txt github_test/test_1_r09.out
echo In test10
diff github_output/output10.txt github_test/test_1_r10.out
echo In test11
diff github_output/output11.txt github_test/test_1_r11.out
echo In test12
diff github_output/output12.txt github_test/test_1_r12.out
