echo In test1
diff myOutput/output1.txt test/test_1_r01.out
echo In test2
diff myOutput/output2.txt test/test_1_r02.out
echo In test3
diff myOutput/output3.txt test/test_1_r03.out
echo In test4
diff myOutput/output4.txt test/test_1_r04.out
echo In test5
diff myOutput/output5.txt test/test_1_r05.out
echo In test6
diff myOutput/output6.txt test/test_1_r06.out
echo In test7
diff myOutput/output7.txt test/test_1_r07.out
echo In test8
diff myOutput/output8.txt test/test_1_r08.out
echo In test9
diff myOutput/output9.txt test/test_1_r09.out
echo In test10
diff myOutput/output10.txt test/test_1_r10.out
echo In test11
diff myOutput/output11.txt test/test_1_r11.out
echo In test12
diff myOutput/output12.txt test/test_1_r12.out
